# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_update_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
