# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_feed_last_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='include_in_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
