# Generated by Django 4.0.3 on 2022-04-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_feed_image_alter_feed_image_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons'),
        ),
    ]
