# Generated by Django 4.0.3 on 2022-04-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_feed_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=400)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
