# Generated by Django 4.0.3 on 2022-04-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_topword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topword',
            options={'ordering': ('-count',)},
        ),
    ]
