# Generated by Django 1.10.5 on 2017-02-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("sort", models.IntegerField(default=1000)),
            ],
            options={
                "ordering": ("-sort",),
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(max_length=400)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("is_new", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "entries",
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(db_index=True, max_length=30)),
                ("url", models.URLField(db_index=True, max_length=250)),
                ("site_url", models.URLField(blank=True, max_length=250, null=True)),
                ("image", models.ImageField(upload_to=b"feedimages")),
                ("sort", models.IntegerField(default=1000)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.Category"
                    ),
                ),
            ],
            options={
                "ordering": ("-sort",),
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.Feed"
            ),
        ),
    ]
