# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_feed_include_in_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='has_adblock_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='has_paywall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to=b'feedimages'),
        ),
        migrations.AddField(
            model_name='feed',
            name='supports_lsr',
            field=models.BooleanField(default=False),
        ),
    ]
