# Generated by Django 1.11.8 on 2018-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_auto_20181117_1632"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
