# Generated by Django 4.0.3 on 2022-04-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181216_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(upload_to='feedimages'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='feedimages'),
        ),
    ]
