# Generated by Django 4.0.3 on 2022-04-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_topword_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="image",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="image_large",
        ),
    ]
