# Generated by Django 4.0.3 on 2022-05-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_feed_image_remove_feed_image_large'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWordLemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TopWordLemmaWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=400)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.topwordlemma')),
            ],
        ),
    ]
