# Generated by Django 4.1.2 on 2022-10-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_topwordlemma_topwordlemmaword"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "Einträge"},
        ),
    ]
