# Generated by Django 5.2.5 on 2025-08-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_entry_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
    ]
